version: '3.8'

services:
  kong:
    image: kong/kong-gateway:3.4
    container_name: kong
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
      - ./kong/kong.env:/etc/kong/kong.env
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_NGINX_DAEMON: "off"
    ports:
      - "8000:8000"   
      - "8001:8001"   
      - "8443:8443"   
      - "8444:8444"   
    networks:
      - kong-network

  user-management-service:
    build: ./user-management-service
    container_name: user-management-service
    ports:
      - "9000:9000"
    networks:
      - kong-network

  staff-dispatch-service:
    build: ./staff-dispatch-service
    container_name: staff-dispatch-service
    ports:
      - "9001:9001"
    networks:
      - kong-network

  redis-server:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - kong-network

networks:
  kong-network:
    driver: bridge