version: '3.8'

services:
  # PostgreSQL database để lưu cấu hình của Kong
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpassword
    ports:
      - "5432:5432"
    networks:
      - kong-network

  # Chạy migration cho Kong
  kong-migrations:
    image: kong/kong-gateway:3.4
    container_name: kong-migrations
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpassword
    command: kong migrations bootstrap
    networks:
      - kong-network

  # Dịch vụ Kong API Gateway
  kong:
    image: kong/kong-gateway:3.4
    container_name: kong
    depends_on:
      - kong-database
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpassword
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"  # Cổng proxy API
      - "8001:8001"  # Cổng quản trị Kong
    networks:
      - kong-network

  # Dịch vụ quản lý người dùng (C# .NET 9)
  user-management-service:
    build: ./user-management-service
    container_name: user-management-service
    ports:
      - "5000:5000"
    networks:
      - kong-network

  # Dịch vụ điều phối nhân viên (Python FastAPI)
  staff-dispatch-service:
    build: ./staff-dispatch-service
    container_name: staff-dispatch-service
    ports:
      - "8002:8002"
    depends_on:
      - user-management-service
    networks:
      - kong-network

  # Redis cache
  redis-server:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - kong-network

networks:
  kong-network:
    driver: bridge
